server:
  port: 8001

spring:
  datasource:
    username: root
    password: 1997
    url: jdbc:mysql://106.15.182.191:3306/micro_manage?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 16
        max-wait: 6000ms
    timeout: 6000ms
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
skywalking:
  webapp:
    url: http://localhost:8081/
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

  #namesrvAddr地址
  qiy:
    rocketmq:
      namesrvAddr: 0.0.0.0:9876
  #生产者group名称
      producerGroupName: microserviceProducer
  #消费者group名称
      consumerGroupName: microserviceConsumer
  #生产者实例名称
      producerInstanceName: producerInstanceName
 # 消费者实例名称
      consumerInstanceName: consumerInstanceName
  #一次最大消费多少数量消息
      consumerBatchMaxSize: 1
  #广播消费
      consumerBroadcasting: false
  #消费的topic：tag
      subscribe:
        - Gateway:route
 # 启动的时候是否消费历史记录
      enableHisConsumer: false
 # 启动顺序消费
      enableOrderConsumer: true
